name: YAML Validation

on:
  push:
    branches:
      - main
    pull_request:
      - main

      
jobs:
  yaml-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Validate YAML
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows/*.yml
          format: github
